### ISSUE TITLE
Add RPM Packaging

### ISSUE THREAD

**Issue by jeffusan** [DecipherNow/gm-fabric-jvm.g8#1]

**Comment by mikejlong60** [comment]
This is almost or maybe even good enough.  Missing is an exact match for the location of the log directory.  My version of the rpm builder is using the default /var/log/notification-service/notification-service-log.  Also missing is the ability to override log4j defaults.  I am working that issue now.  Need to add the application's etc directory to the classpath.

**Comment by mikejlong60** [comment]
I just added the ability to override log4j defaults by adding the application's etc directory first in the classpath.
